# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/swimshop
spring.datasource.username=postgres
spring.datasource.password=????_??????
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# App name
spring.application.name=swimshop
spring.jpa.open-in-view=false